# Site settings
title: (bio) Fluids
subtitle: always have an escape plan
email: caruvalcaba@ucdavis.edu
description: Welcome to Carlos' webpage on biofluid mechanics research, teaching, and other worldly escapes from the academic life.
# baseurl: "/editorial-jekyll-theme" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Carlos Abraham Ruvalcaba
street_address: 2131 Bainer Hall, One Shields Avenue
city: Davis
state: California
zip_code: 95616
country: United States of America
phone: (530) 123-4567

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/carlos-ar
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/carlosar-cfd
pinterest_url:
slack_url:
twitter_url: https://twitter.com/carlosarv19

# Build settings
markdown: kramdown

# adding stuff for pages
paginate: 3
paginate_path: "/updates/page:num/"

# adding collections
collections_dir: collections
collections:
  pretty_pictures:
    sort_by: lesson
    output: true
    permalink: /teaching/:collection/:name
  ucleads2020:
    sort_by: lesson
    output: true
    permalink: /teaching/ucleads/:name


# excerpts
excerpt_separator: <!--more-->